apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:klapxdB+ixp2sK1nNVc3N/0rdxLm6cHT,iv:WAS4PUSX2jkOgyRJ+yNdHG7wsDV6k3uj30vDVh/6cBU=,tag:i+6qluivfrKD6DXSrcbjdA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:pCVPINvAGZQMPSL41JLetREgIiD2wLhFmMkC4iHyEEG8rBenMw==,iv:XvxwlZcrey8I1h6BTqFElehfwVWBowzGVR2ichXtuT8=,tag:ekC8FdD5NkUuzI1QkWRahg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:9QUGM6uJ/5Vo/XTbyA==,iv:PoTocmxsvRuYbKzTRr/mM8uemjqxp8W30cvDN8qOmhk=,tag:gzuCyByNNjcQIihUVahxWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wfkpt9lnzznznnmxum68j9v359u82ltpng8a00cynyf65qx2mdasshc9ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQzFSZ0wyT213OUFqRU9s
            VFM0cjh1RDNpWWhwTjdrSlJNTjhoL3lUOVNNClc4MEhzamc3Vnh5MlQvZlJiQUVh
            Nlp3YjJxREhEbngvSDQra01oRU93YVkKLS0tIHNxMFZjZEkzV05lL3lXUUlEbmNC
            V1M5OEUxOGxtZmxLT0F6Y3NvNlpwdHcKjPFs80x1kkQO4Y4HHEDiVu6GYAGv5FLB
            qCt4wtHpdTixb4qDno/+2ISJ0k0PLMSCg0jOnXVhahpeqci4kpWoVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T20:36:36Z"
    mac: ENC[AES256_GCM,data:TZPVWBMKc/13b86hekANV6q51ApEFDhvlZOSo3s+JqnK0ipFH/zOLsYAw8MjZNr/E5YEM1qZIdBuDilKYDCyJRgZA05EOzAgNt+R4DZfuPS/7Yf3mGfC+DrItdk3jKMF16ZnfU3o6eSOzRlSSsBzkv2Xg565VHfp2Xrx2zsJiLI=,iv:g7sx1cf9WQKx81svOZosm7Rug69RJgyc8a8yaGFBAKg=,tag:w2oq4chP5AviHxbxoeBneQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
