---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1k66u9f5uhppplvp93jzkvqclp9n8w9rxl3dnur28fevmnvxd0cgqy56t39
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1k66u9f5uhppplvp93jzkvqclp9n8w9rxl3dnur28fevmnvxd0cgqy56t39
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1k66u9f5uhppplvp93jzkvqclp9n8w9rxl3dnur28fevmnvxd0cgqy56t39
