---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1wfkpt9lnzznznnmxum68j9v359u82ltpng8a00cynyf65qx2mdasshc9ps
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1wfkpt9lnzznznnmxum68j9v359u82ltpng8a00cynyf65qx2mdasshc9ps
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1wfkpt9lnzznznnmxum68j9v359u82ltpng8a00cynyf65qx2mdasshc9ps
