apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:MpPZdsQMPZek+IT2db7kbrBuB5Ot4srsbeQCgHIGcV6DCVOWdQ==,iv:BExcsIdWPsXBeRCAUpfoqCbip0jr+mhZrTuSLrBEoOo=,tag:C5OC+Jc0IvGmjufY566FpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wfkpt9lnzznznnmxum68j9v359u82ltpng8a00cynyf65qx2mdasshc9ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYmdPNG5ITXNCb2ZiaVNL
            SFgyQWdQbHlyMWNXOUc3SWk3RFdUM1QycmpBCjlaQmw4clp0WlFJWTd4bHk0bFBK
            MTBieHpTTFl4TnkxR2sxUDNadGw3dkEKLS0tIEZWY2xxZnBteUtPdmRJcCtYU045
            OHVEZ3JzNENJbis3ZGlCZC8yMGpHYUUKJ/2dEw8JX7x9u1wCFHwK367O6pXhew1Q
            ELuzJsZWGF0Jzgiy5fH1FmqfApKda/Wh8GmNZPGi+EuHgGcXR2qGWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T20:36:36Z"
    mac: ENC[AES256_GCM,data:cEE6QnkPAqFYmbLAl48hb8uM0+xfyADt+0mpvY3HMWhrp5wDaJ7JSHhACq7xkr6eyTLmOWl1/JSDXHPtsxoP67K199udWMdcvdg73hMNr62flauX3s7CANNOJ+O/eJkRbNlExItG9bSRKPXw7p32/mi6e1vzcQ0KLQ+nWlYYB4I=,iv:oVe7xlD/vMC5UXzdVBfHMv+m7fjO7TArwKT2S0fFIeE=,tag:azWYz2oIVbHrjDrZ9Zsm6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
