---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "192.168.1.211"
  METALLB_LB_RANGE: "192.168.1.200-192.168.1.210"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.200"
  METALLB_INGRESS_ADDR: "192.168.1.201"
